# ─── Azure AI Language ───────────────────────────────────────────
AZURE_LANGUAGE_ENDPOINT = "YOUR_LANGUAGE_ENDPOINT_HERE"
AZURE_LANGUAGE_KEY = "YOUR_LANGUAGE_KEY_HERE"

# ─── Azure AI Search (Cognitive Search) ─────────────────────────
AZURE_SEARCH_ENDPOINT = "YOUR_SEARCH_ENDPOINT_HERE"
AZURE_SEARCH_KEY = "YOUR_SEARCH_ADMIN_KEY_HERE"
AZURE_SEARCH_INDEX_NAME = "YOUR_SEARCH_INDEX_NAME_HERE"

# ─── Azure AI Translator ─────────────────────────────────────────
AZURE_TRANSLATOR_ENDPOINT = "YOUR_TRANSLATOR_ENDPOINT_HERE"
AZURE_TRANSLATOR_KEY = "YOUR_TRANSLATOR_KEY_HERE"
AZURE_TRANSLATOR_REGION = "YOUR_TRANSLATOR_REGION_HERE"

# ─── Azure AI Vision (Computer Vision) ──────────────────────────
AZURE_VISION_ENDPOINT = "YOUR_VISION_ENDPOINT_HERE"
AZURE_VISION_KEY = "YOUR_VISION_KEY_HERE"

# ─── Azure OpenAI Service ────────────────────────────────────────
AZURE_OPENAI_ENDPOINT = "YOUR_OPENAI_ENDPOINT_HERE"
AZURE_OPENAI_KEY = "YOUR_OPENAI_KEY_HERE"
AZURE_OPENAI_DEPLOYMENT_NAME = "YOUR_DEPLOYMENT_NAME_HERE"
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"
